In [1]:
import pandas as pd
pd.options.display.max_columns = 70 #Para ver todas las columas ya que sin esto se mostrarian solo algunas

df = pd.read_csv("raw data/Combined_Flights_2021.csv", encoding="cp1252", on_bad_lines="skip")

In [2]:
# Información básica y primeras filas
print("Filas:", len(df))
print("Columnas:", len(df.columns))
display(df.info())

Filas: 6311871
Columnas: 61
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6311871 entries, 0 to 6311870
Data columns (total 61 columns):
 #   Column                                   Dtype
---  ------                                   -----
 0   FlightDate                               object
 1   Airline                                  object
 2   Origin                                   object
 3   Dest                                     object
 4   Cancelled                                bool
 5   Diverted                                 bool
 6   CRSDepTime                               int64
 7   DepTime                                  float64
 8   DepDelayMinutes                          float64
 9   DepDelay                                 float64
 10  ArrTime                                  float64
 11  ArrDelayMinutes                          float64
 12  AirTime                                  float64
 13  CRSElapsedTime                           float64
 14  ActualElapsedTime                        float64
 15  Distance                                 float64
 16  Year                                     int64
 17  Quarter                                  int64
 18  Month                                    int64
 19  DayofMonth                               int64
 20  DayOfWeek                                int64
 21  Marketing_Airline_Network                object
 22  Operated_or_Branded_Code_Share_Partners  object
 23  DOT_ID_Marketing_Airline                 int64
 24  IATA_Code_Marketing_Airline              object
 25  Flight_Number_Marketing_Airline          int64
 26  Operating_Airline                        object
 27  DOT_ID_Operating_Airline                 int64
 28  IATA_Code_Operating_Airline              object
 29  Tail_Number                              object
 30  Flight_Number_Operating_Airline          int64
 31  OriginAirportID                          int64
 32  OriginAirportSeqID                       int64
 33  OriginCityMarketID                       int64
 34  OriginCityName                           object
 35  OriginState                              object
 36  OriginStateFips                          int64
 37  OriginStateName                          object
 38  OriginWac                                int64
 39  DestAirportID                            int64
 40  DestAirportSeqID                         int64
 41  DestCityMarketID                         int64
 42  DestCityName                             object
 43  DestState                                object
 44  DestStateFips                            int64
 45  DestStateName                            object
 46  DestWac                                  int64
 47  DepDel15                                 float64
 48  DepartureDelayGroups                     float64
 49  DepTimeBlk                               object
 50  TaxiOut                                  float64
 51  WheelsOff                                float64
 52  WheelsOn                                 float64
 53  TaxiIn                                   float64
 54  CRSArrTime                               int64
 55  ArrDelay                                 float64
 56  ArrDel15                                 float64
 57  ArrivalDelayGroups                       float64
 58  ArrTimeBlk                               object
 59  DistanceGroup                            int64
 60  DivAirportLandings                       float64
dtypes: bool(2), float64(19), int64(22), object(18)
memory usage: 2.8+ GB

None

In [3]:
display(df.head())

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2021-03-03,SkyWest Airlines Inc.,SGU,PHX,False,False,724,714.0,0.0,-10.0,818.0,0.0,49.0,79.0,64.0,262.0,2021,1,3,3,3,AA,AA_CODESHARE,19805,AA,3133,OO,20304,OO,N728SK,3133,14794,1479405,34794,"St. George, UT",UT,49,Utah,87,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,0.0,-1.0,0700-0759,10.0,724.0,813.0,5.0,843,-25.0,0.0,-2.0,0800-0859,2,0.0
1,2021-03-03,SkyWest Airlines Inc.,PHX,SGU,False,False,922,917.0,0.0,-5.0,1031.0,0.0,48.0,78.0,74.0,262.0,2021,1,3,3,3,AA,AA_CODESHARE,19805,AA,3134,OO,20304,OO,N752SK,3134,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,14794,1479405,34794,"St. George, UT",UT,49,Utah,87,0.0,-1.0,0900-0959,23.0,940.0,1028.0,3.0,1040,-9.0,0.0,-1.0,1000-1059,2,0.0
2,2021-03-03,SkyWest Airlines Inc.,MHT,ORD,False,False,1330,1321.0,0.0,-9.0,1501.0,0.0,129.0,180.0,160.0,843.0,2021,1,3,3,3,AA,AA_CODESHARE,19805,AA,3135,OO,20304,OO,N766SK,3135,13296,1329604,30721,"Manchester, NH",NH,33,New Hampshire,14,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,1300-1359,15.0,1336.0,1445.0,16.0,1530,-29.0,0.0,-2.0,1500-1559,4,0.0
3,2021-03-03,SkyWest Airlines Inc.,DFW,TRI,False,False,1645,1636.0,0.0,-9.0,2002.0,0.0,112.0,145.0,146.0,868.0,2021,1,3,3,3,AA,AA_CODESHARE,19805,AA,3136,OO,20304,OO,N752EV,3136,11298,1129806,30194,"Dallas/Fort Worth, TX",TX,48,Texas,74,15323,1532305,35323,"Bristol/Johnson City/Kingsport, TN",TN,47,Tennessee,54,0.0,-1.0,1600-1659,27.0,1703.0,1955.0,7.0,2010,-8.0,0.0,-1.0,2000-2059,4,0.0
4,2021-03-03,SkyWest Airlines Inc.,PHX,BFL,False,False,1844,1838.0,0.0,-6.0,1903.0,0.0,69.0,101.0,85.0,425.0,2021,1,3,3,3,AA,AA_CODESHARE,19805,AA,3137,OO,20304,OO,N715SK,3137,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,10561,1056103,30561,"Bakersfield, CA",CA,6,California,91,0.0,-1.0,1800-1859,13.0,1851.0,1900.0,3.0,1925,-22.0,0.0,-2.0,1900-1959,2,0.0

In [4]:
# conteo de nulos y porcentaje del dataset que representan
N = len(df)
na_df = pd.DataFrame({
    "column": df.columns,
    "na_count": df.isna().sum().values
})
na_df["na_pct"] = (na_df["na_count"] / N) * 100
na_df = na_df.sort_values("na_count", ascending=False).reset_index(drop=True)
# Muestro todas las columnas ordenadas por nulos. 
display(na_df.head(20))

# porcentaje total de celdas nulas en todo el dataset
total_na = df.isna().sum().sum()
total_cells = N * df.shape[1]
total_na_pct = (total_na / total_cells) * 100
print(f"Total celdas: {total_cells:,}")
print(f"Celdas con NA: {total_na:,}  ({total_na_pct:.4f} % del dataset total)")

                  column  na_count    na_pct
0        ArrDelayMinutes    126001  1.996254
1      ActualElapsedTime    126001  1.996254
2                AirTime    126001  1.996254
3     ArrivalDelayGroups    126001  1.996254
4               ArrDel15    126001  1.996254
5               ArrDelay    126001  1.996254
6               WheelsOn    112425  1.781168
7                 TaxiIn    112425  1.781168
8                ArrTime    112408  1.780898
9              WheelsOff    110353  1.748341
10               TaxiOut    110353  1.748341
11              DepDelay    108413  1.717605
12              DepDel15    108413  1.717605
13  DepartureDelayGroups    108413  1.717605
14       DepDelayMinutes    108413  1.717605
15               DepTime    108325  1.716211
16           Tail_Number     23303  0.369193
17    DivAirportLandings         2  0.000032
18        CRSElapsedTime         1  0.000016
19           OriginState         0  0.000000

Total celdas: 385,024,131
Celdas con NA: 1,879,253  (0.4881 % del dataset total)

In [5]:
# Conteo total de ceros y conteo por columna
import pandas as pd
data = df

total_cells = data.shape[0] * data.shape[1]
zero_counts = 0
rows = []

for c in data.columns:
    ser = data[c]
    if pd.api.types.is_numeric_dtype(ser):
        z = (ser == 0).sum()
    else:
        z = ser.astype(str).str.strip().isin(["0", "0.0"]).sum()
    pct_rows = (z / len(data)) * 100
    rows.append((c, int(z), round(pct_rows, 4)))
    zero_counts += int(z)

zero_pct_total = (zero_counts / total_cells) * 100 if total_cells > 0 else 0.0

zero_df = pd.DataFrame(rows, columns=['column', 'zero_count', 'zero_pct_rows']).sort_values('zero_count', ascending=False).reset_index(drop=True)

print(f"Total celdas: {total_cells:,}")
print(f"Celdas con valor 0: {zero_counts:,}  ({zero_pct_total:.4f} % del dataset total)")
display(zero_df.head(11)) # solo las primeras 11 tienen 0s y para no hacer tan largo el output

Total celdas: 385,024,131
Celdas con valor 0: 40,141,852  (10.4258 % del dataset total)

                  column  zero_count  zero_pct_rows
0               Diverted     6296889        99.7626
1     DivAirportLandings     6296222        99.7521
2              Cancelled     6200853        98.2411
3               DepDel15     5129191        81.2626
4               ArrDel15     5117811        81.0823
5        ArrDelayMinutes     4166398        66.0089
6        DepDelayMinutes     4147768        65.7138
7   DepartureDelayGroups     1292454        20.4766
8     ArrivalDelayGroups     1067324        16.9098
9               DepDelay      311031         4.9277
10              ArrDelay      115911         1.8364

Una vez obtenido los porcentajes de 0s y nulos en el dataset hay que ver si se pueden eliminar (dropear) o si, se pueden inferir de alguna manera.

1. Aunque son valores que se pueden inferir, ya que el dataset cuenta con un porcentaje muy bajo de nulos (0.8%) lo dropeo.
2. Todas las variables que contienen un porcentaje de 0s tienen sentido ya que o son booleanas o tienen posibilidad de serlo.

In [6]:
# Creación de un nuevo DataFrame sin valores NA
df_clean = df.copy()
df_clean = df_clean.dropna(axis=0, how='any').reset_index(drop=True)
print("Shape original df:", df.shape)
print("Shape df_clean (sin NA):", df_clean.shape)

Shape original df: (6311871, 61)
Shape df_clean (sin NA): (6185869, 61)

In [7]:
cancelled_flights = df[df['Cancelled'] == 1]
print("Número de vuelos cancelados:", len(cancelled_flights))

Número de vuelos cancelados: 111018

Elimino columnas que no son necesarias, como las de fecha que son todas derivables de una misma. Las elimino para no sobrecargar tanto a la hora de manejar datos ya que son demasiadas columnas.

In [8]:
# Eliminar columnas derivables de Date
cols_to_drop = ['Year','Quarter','Month','DayofMonth','DayOfWeek']
existing = [c for c in cols_to_drop if c in df_clean.columns]
print("Columnas a eliminar (existentes):", existing)
df_clean = df_clean.drop(columns=existing, errors='ignore')
print("Shape tras eliminar columnas derivables:", df_clean.shape)

Columnas a eliminar (existentes): ['Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek']
Shape tras eliminar columnas derivables: (6185869, 56)

In [9]:
# filtrar por distancia irreal, manteniendo cancelados
threshold = 3  # millas
before = df_clean.shape[0]

# Normalizar nombre de columna Cancelled si hay variantes
cancel_col = None
for name in ['CANCELLED','Cancelled','Cancelled','Cancelled']:
    if name in df_clean.columns:
        cancel_col = name
        break

if 'Distance' not in df_clean.columns:
    print("Atención: no existe la columna 'Distance' en df_clean.")
else:
    # crear máscara: True para filas a mantener
    if cancel_col:
        keep_mask = (df_clean['Distance'] > threshold) | (df_clean[cancel_col] == 1)
    else:
        keep_mask = (df_clean['Distance'] > threshold)
    df_clean = df_clean[keep_mask].reset_index(drop=True)
    after = df_clean.shape[0]
    print(f"Filas antes: {before}, Filas después del filtro de distancia (umbral={threshold}): {after}, Filas eliminadas: {before-after}")

Filas antes: 6185869, Filas después del filtro de distancia (umbral=3): 6185869, Filas eliminadas: 0

Normalizo el formato HHMM para que se pueda intepretar correctamente los Strings y no confundirme con minutos, horas, o lo que fuese.

In [10]:
# Normalizar columnas de tiempo a formato HHMM (strings de 4 dígitos)
cols_time = ['CRSDepTime','CRSArrTime','DepTime','ArrTime']

for c in cols_time:
    if c in df_clean.columns:
        # Convertir a string, quitar espacios, rellenar con ceros a la izquierda
        df_clean[c] = df_clean[c].astype(str).str.strip().str.zfill(4)
        # Reemplazar valores 'NaN' que se convirtieron en string por np.nan
        df_clean[c] = df_clean[c].replace({'NaN': pd.NA, 'nan': pd.NA})
        
print("Ejemplo de valores normalizados:")
for c in cols_time:
    if c in df_clean.columns:
        print(c, "->", df_clean[c].dropna().unique()[:10])

Ejemplo de valores normalizados:
CRSDepTime -> ['0724' '0922' '1330' '1645' '1844' '1650' '1652' '1245' '0726' '2045']
CRSArrTime -> ['0843' '1040' '1530' '2010' '1925' '1834' '1902' '1456' '0836' '2215']
DepTime -> ['714.0' '917.0' '1321.0' '1636.0' '1838.0' '1648.0' '1651.0' '1242.0'
 '717.0' '2040.0']
ArrTime -> ['818.0' '1031.0' '1501.0' '2002.0' '1903.0' '1808.0' '1929.0' '1452.0'
 '821.0' '2144.0']

In [11]:
import pandas as pd

# Detectar nombre de columna de fecha
fecha_col = 'FlightDate'
 
# Convertir columna de fecha a datetime
df_clean[fecha_col] = pd.to_datetime(df_clean[fecha_col], errors='coerce')

# Función para limpiar HHMM
def clean_hhmm(series):
    return (
        series.astype(str)
        .str.replace(r'\.0$', '', regex=True)   # quitar ".0"
        .str.replace(r'\D', '', regex=True)     # quitar caracteres no numéricos
        .str.zfill(4)                           # rellenar a 4 dígitos
        .replace({'NaN': pd.NA, 'nan': pd.NA})
    )

# Normalizar columnas de tiempo
for c in ['CRSDepTime','CRSArrTime','DepTime','ArrTime']:
    if c in df_clean.columns:
        df_clean[c] = clean_hhmm(df_clean[c])

# Crear datetimes programados
if 'CRSDepTime' in df_clean.columns:
    hhmm = df_clean['CRSDepTime'].dropna()
    df_clean.loc[hhmm.index, 'sched_dep_dt'] = pd.to_datetime(df_clean.loc[hhmm.index, fecha_col]) + \
        pd.to_timedelta(hhmm.str[:2].astype(int), unit='h') + \
        pd.to_timedelta(hhmm.str[2:].astype(int), unit='m')

if 'CRSArrTime' in df_clean.columns:
    hhmm = df_clean['CRSArrTime'].dropna()
    df_clean.loc[hhmm.index, 'sched_arr_dt'] = pd.to_datetime(df_clean.loc[hhmm.index, fecha_col]) + \
        pd.to_timedelta(hhmm.str[:2].astype(int), unit='h') + \
        pd.to_timedelta(hhmm.str[2:].astype(int), unit='m')

# Crear datetimes reales (solo si existen valores)
if 'DepTime' in df_clean.columns:
    hhmm = df_clean['DepTime'].dropna()
    df_clean.loc[hhmm.index, 'dep_dt'] = pd.to_datetime(df_clean.loc[hhmm.index, fecha_col]) + \
        pd.to_timedelta(hhmm.str[:2].astype(int), unit='h') + \
        pd.to_timedelta(hhmm.str[2:].astype(int), unit='m')

if 'ArrTime' in df_clean.columns:
    hhmm = df_clean['ArrTime'].dropna()
    df_clean.loc[hhmm.index, 'arr_dt'] = pd.to_datetime(df_clean.loc[hhmm.index, fecha_col]) + \
        pd.to_timedelta(hhmm.str[:2].astype(int), unit='h') + \
        pd.to_timedelta(hhmm.str[2:].astype(int), unit='m')

print(df_clean[['CRSDepTime','sched_dep_dt','DepTime','dep_dt']].head(10))

  CRSDepTime        sched_dep_dt DepTime              dep_dt
0       0724 2021-03-03 07:24:00    0714 2021-03-03 07:14:00
1       0922 2021-03-03 09:22:00    0917 2021-03-03 09:17:00
2       1330 2021-03-03 13:30:00    1321 2021-03-03 13:21:00
3       1645 2021-03-03 16:45:00    1636 2021-03-03 16:36:00
4       1844 2021-03-03 18:44:00    1838 2021-03-03 18:38:00
5       1650 2021-03-03 16:50:00    1648 2021-03-03 16:48:00
6       1652 2021-03-03 16:52:00    1651 2021-03-03 16:51:00
7       1245 2021-03-03 12:45:00    1242 2021-03-03 12:42:00
8       0726 2021-03-03 07:26:00    0717 2021-03-03 07:17:00
9       2045 2021-03-03 20:45:00    2040 2021-03-03 20:40:00

Elimino columnas de tiempos originales porque ya cree las variables datetime y no necesito duplicados. Ademas que evidentemente, el tener tantos datos y columnas consume mucho tiempo y recursos. FlightDate la mantengo porque es mas compacto para graficas/analisis que no son por hora,etc.

In [12]:
df_clean = df_clean.drop(columns=['CRSDepTime','CRSArrTime','DepTime','ArrTime'], errors='ignore')
# Reorganizar columnas: poner FlightDate primero, luego las nuevas datetime, luego el resto
cols_base = list(df_clean.columns)
fecha_col = 'FlightDate'  
cols_new = ['sched_dep_dt','sched_arr_dt','dep_dt','arr_dt']
ordered_cols = [fecha_col] + [c for c in cols_new if c in cols_base] + [c for c in cols_base if c not in ([fecha_col] + cols_new)]
df_clean = df_clean[ordered_cols]
df_clean.head()

,FlightDate,sched_dep_dt,sched_arr_dt,dep_dt,arr_dt,Airline,Origin,Dest,Cancelled,Diverted,DepDelayMinutes,DepDelay,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2021-03-03,2021-03-03 07:24:00,2021-03-03 08:43:00,2021-03-03 07:14:00,2021-03-03 08:18:00,SkyWest Airlines Inc.,SGU,PHX,False,False,0.0,-10.0,0.0,49.0,79.0,64.0,262.0,AA,AA_CODESHARE,19805,AA,3133,OO,20304,OO,N728SK,3133,14794,1479405,34794,"St. George, UT",UT,49,Utah,87,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,0.0,-1.0,0700-0759,10.0,724.0,813.0,5.0,-25.0,0.0,-2.0,0800-0859,2,0.0
1,2021-03-03,2021-03-03 09:22:00,2021-03-03 10:40:00,2021-03-03 09:17:00,2021-03-03 10:31:00,SkyWest Airlines Inc.,PHX,SGU,False,False,0.0,-5.0,0.0,48.0,78.0,74.0,262.0,AA,AA_CODESHARE,19805,AA,3134,OO,20304,OO,N752SK,3134,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,14794,1479405,34794,"St. George, UT",UT,49,Utah,87,0.0,-1.0,0900-0959,23.0,940.0,1028.0,3.0,-9.0,0.0,-1.0,1000-1059,2,0.0
2,2021-03-03,2021-03-03 13:30:00,2021-03-03 15:30:00,2021-03-03 13:21:00,2021-03-03 15:01:00,SkyWest Airlines Inc.,MHT,ORD,False,False,0.0,-9.0,0.0,129.0,180.0,160.0,843.0,AA,AA_CODESHARE,19805,AA,3135,OO,20304,OO,N766SK,3135,13296,1329604,30721,"Manchester, NH",NH,33,New Hampshire,14,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,1300-1359,15.0,1336.0,1445.0,16.0,-29.0,0.0,-2.0,1500-1559,4,0.0
3,2021-03-03,2021-03-03 16:45:00,2021-03-03 20:10:00,2021-03-03 16:36:00,2021-03-03 20:02:00,SkyWest Airlines Inc.,DFW,TRI,False,False,0.0,-9.0,0.0,112.0,145.0,146.0,868.0,AA,AA_CODESHARE,19805,AA,3136,OO,20304,OO,N752EV,3136,11298,1129806,30194,"Dallas/Fort Worth, TX",TX,48,Texas,74,15323,1532305,35323,"Bristol/Johnson City/Kingsport, TN",TN,47,Tennessee,54,0.0,-1.0,1600-1659,27.0,1703.0,1955.0,7.0,-8.0,0.0,-1.0,2000-2059,4,0.0
4,2021-03-03,2021-03-03 18:44:00,2021-03-03 19:25:00,2021-03-03 18:38:00,2021-03-03 19:03:00,SkyWest Airlines Inc.,PHX,BFL,False,False,0.0,-6.0,0.0,69.0,101.0,85.0,425.0,AA,AA_CODESHARE,19805,AA,3137,OO,20304,OO,N715SK,3137,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,10561,1056103,30561,"Bakersfield, CA",CA,6,California,91,0.0,-1.0,1800-1859,13.0,1851.0,1900.0,3.0,-22.0,0.0,-2.0,1900-1959,2,0.0

**Normalizacion de IATAs**

La normalizacion se aplica a las columnas Origin, Dest, IATA_Code_Operating_Airline e IATA_Code_Marketing_Airline porque todas contienen codigos IATA que deben estar en un formato uniforme. 

El proceso convierte los valores a tipo string, elimina espacios en blanco, pasa todo a mayusculas y quita caracteres no alfabeticos. Esto asegura que los codigos de aeropuertos y aerolineas se comparen de forma consistente, evita duplicados por diferencias de formato y permite hacer merges y agrupaciones sin errores.

In [13]:
# Normalizar codigos IATA de aeropuertos y aerolineas
for c in ['Origin','Dest','IATA_Code_Operating_Airline','IATA_Code_Marketing_Airline']:
    if c in df_clean.columns:
        df_clean[c] = (
            df_clean[c]
            .astype(str)              
            .str.strip()              
            .str.upper()              
            .str.replace(r'[^A-Z]', '', regex=True)
        )

# Comprobar ejemplos de valores unicos
for c in ['Origin','Dest','IATA_Code_Operating_Airline','IATA_Code_Marketing_Airline']:
    if c in df_clean.columns:
        print(f"Valores unicos en {c}:", df_clean[c].unique()[:20])

Valores unicos en Origin: ['SGU' 'PHX' 'MHT' 'DFW' 'ORD' 'PSP' 'LBB' 'FWA' 'DRO' 'LAX' 'SFO' 'JLN'
 'SAF' 'ASE' 'HRL' 'DTW' 'GJT' 'SLC' 'FSM' 'FLG']
Valores unicos en Dest: ['PHX' 'SGU' 'ORD' 'TRI' 'BFL' 'BNA' 'YUM' 'DRO' 'FAR' 'ABQ' 'ASE' 'SFO'
 'LAX' 'DFW' 'JLN' 'OKC' 'FSM' 'HRL' 'MFR' 'SBP']
Valores unicos en IATA_Code_Operating_Airline: ['OO' 'QX' 'UA' 'C' 'G' 'ZW' 'WN' 'YV' 'YX' 'NK' 'DL' 'F' 'HA' 'MQ' 'OH'
 'E' 'AA' 'PT' 'AS' 'B']
Valores unicos en IATA_Code_Marketing_Airline: ['AA' 'DL' 'UA' 'AS' 'WN' 'NK' 'F' 'G' 'HA' 'B']

In [14]:
for c in ['Cancelled','Diverted']:
    if c in df_clean.columns:
        df_clean[c] = df_clean[c].astype('bool').astype('int')

In [15]:
out_path = "Conbined_Flights_Limpio.csv"
try:
    df_clean.to_csv(out_path, index=False, encoding="utf-8")
    print(f"Guardado: {out_path} — filas: {df_clean.shape[0]}, columnas: {df_clean.shape[1]}")
except Exception as e:
    print("Error al guardar:", e)

Guardado: Conbined_Flights_Limpio.csv — filas: 6185869, columnas: 56

**Chequeo de que se exporto a csv correctamente**

In [16]:
import pandas as pd

df_chequeo = pd.read_csv("Conbined_Flights_Limpio.csv", encoding="utf-8")
df_chequeo.head()

,FlightDate,sched_dep_dt,sched_arr_dt,dep_dt,arr_dt,Airline,Origin,Dest,Cancelled,Diverted,DepDelayMinutes,DepDelay,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2021-03-03,2021-03-03 07:24:00,2021-03-03 08:43:00,2021-03-03 07:14:00,2021-03-03 08:18:00,SkyWest Airlines Inc.,SGU,PHX,0,0,0.0,-10.0,0.0,49.0,79.0,64.0,262.0,AA,AA_CODESHARE,19805,AA,3133,OO,20304,OO,N728SK,3133,14794,1479405,34794,"St. George, UT",UT,49,Utah,87,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,0.0,-1.0,0700-0759,10.0,724.0,813.0,5.0,-25.0,0.0,-2.0,0800-0859,2,0.0
1,2021-03-03,2021-03-03 09:22:00,2021-03-03 10:40:00,2021-03-03 09:17:00,2021-03-03 10:31:00,SkyWest Airlines Inc.,PHX,SGU,0,0,0.0,-5.0,0.0,48.0,78.0,74.0,262.0,AA,AA_CODESHARE,19805,AA,3134,OO,20304,OO,N752SK,3134,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,14794,1479405,34794,"St. George, UT",UT,49,Utah,87,0.0,-1.0,0900-0959,23.0,940.0,1028.0,3.0,-9.0,0.0,-1.0,1000-1059,2,0.0
2,2021-03-03,2021-03-03 13:30:00,2021-03-03 15:30:00,2021-03-03 13:21:00,2021-03-03 15:01:00,SkyWest Airlines Inc.,MHT,ORD,0,0,0.0,-9.0,0.0,129.0,180.0,160.0,843.0,AA,AA_CODESHARE,19805,AA,3135,OO,20304,OO,N766SK,3135,13296,1329604,30721,"Manchester, NH",NH,33,New Hampshire,14,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,1300-1359,15.0,1336.0,1445.0,16.0,-29.0,0.0,-2.0,1500-1559,4,0.0
3,2021-03-03,2021-03-03 16:45:00,2021-03-03 20:10:00,2021-03-03 16:36:00,2021-03-03 20:02:00,SkyWest Airlines Inc.,DFW,TRI,0,0,0.0,-9.0,0.0,112.0,145.0,146.0,868.0,AA,AA_CODESHARE,19805,AA,3136,OO,20304,OO,N752EV,3136,11298,1129806,30194,"Dallas/Fort Worth, TX",TX,48,Texas,74,15323,1532305,35323,"Bristol/Johnson City/Kingsport, TN",TN,47,Tennessee,54,0.0,-1.0,1600-1659,27.0,1703.0,1955.0,7.0,-8.0,0.0,-1.0,2000-2059,4,0.0
4,2021-03-03,2021-03-03 18:44:00,2021-03-03 19:25:00,2021-03-03 18:38:00,2021-03-03 19:03:00,SkyWest Airlines Inc.,PHX,BFL,0,0,0.0,-6.0,0.0,69.0,101.0,85.0,425.0,AA,AA_CODESHARE,19805,AA,3137,OO,20304,OO,N715SK,3137,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,10561,1056103,30561,"Bakersfield, CA",CA,6,California,91,0.0,-1.0,1800-1859,13.0,1851.0,1900.0,3.0,-22.0,0.0,-2.0,1900-1959,2,0.0

**Union con el Dataset de Aeropuertos**

Ahora que la limpieza esta terminada paso a unirlo con el otro dataset secundario descargado. Para esto tenia que tener una llave que pueda utilizarse para conbinar ambos datasets como es el IATA Code.

In [17]:
import pandas as pd
airports_path = "raw data/airports.csv" 
airports = pd.read_csv(airports_path, dtype=str)

airports = airports.rename(columns={col: col.strip() for col in airports.columns})
airports = airports[['iata_code','name','latitude_deg','longitude_deg','iso_country']]
# Normalizar iata_code y convertir lat/lon a numerico
airports['iata_code'] = airports['iata_code'].astype(str).str.strip().str.upper()
airports['latitude_deg'] = pd.to_numeric(airports['latitude_deg'], errors='coerce')
airports['longitude_deg'] = pd.to_numeric(airports['longitude_deg'], errors='coerce')


# Merge para origen (left join)
df_merged = df_clean.merge(
    airports[['iata_code','latitude_deg','longitude_deg']].rename(
        columns={'iata_code':'Origin_iata','latitude_deg':'origin_lat','longitude_deg':'origin_lon'}
    ),
    how='left',
    left_on='Origin',
    right_on='Origin_iata'
).drop(columns=['Origin_iata'])

# Merge para destino (left join)
df_merged = df_merged.merge(
    airports[['iata_code','latitude_deg','longitude_deg']].rename(
        columns={'iata_code':'Dest_iata','latitude_deg':'dest_lat','longitude_deg':'dest_lon'}
    ),
    how='left',
    left_on='Dest',
    right_on='Dest_iata'
).drop(columns=['Dest_iata'])

# Comprobaciones y reporte rapido
missing_origin = df_merged['origin_lat'].isna().sum()
missing_dest = df_merged['dest_lat'].isna().sum()
total = len(df_merged)
print(f"Faltan coords origen: {missing_origin} / {total}")
print(f"Faltan coords destino: {missing_dest} / {total}")

# Opcional: listar codigos IATA sin match (para inspeccion)
missing_orig_codes = (df_merged[df_merged['origin_lat'].isna()]['Origin']
                      .drop_duplicates().sort_values().tolist())
missing_dest_codes = (df_merged[df_merged['dest_lat'].isna()]['Dest']
                      .drop_duplicates().sort_values().tolist())
print("Origin sin match (ejemplos):", missing_orig_codes[:20])
print("Dest sin match (ejemplos):", missing_dest_codes[:20])

Faltan coords origen: 39629 / 6185869
Faltan coords destino: 39932 / 6185869
Origin sin match (ejemplos): ['BQN', 'GUM', 'PPG', 'PSE', 'SJU', 'SPN', 'STT', 'STX']
Dest sin match (ejemplos): ['BQN', 'GUM', 'PPG', 'PSE', 'SJU', 'SPN', 'STT', 'STX']

In [18]:
# Análisis de filas sin coordenadas
total = len(df_merged)
missing_origin = df_merged['origin_lat'].isna()
missing_dest = df_merged['dest_lat'].isna()
missing_either = missing_origin | missing_dest
n_missing = missing_either.sum()

# Porcentajes resumidos
pct_missing = n_missing / total * 100
pct_cancelled_of_missing = df_merged.loc[missing_either, 'Cancelled'].mean() * 100
pct_diverted_of_missing = df_merged.loc[missing_either, 'Diverted'].mean() * 100

print(f"Filas sin coords: {n_missing:,} / {total:,} ({pct_missing:.3f}%)")
print(f"De esas: Cancelled {pct_cancelled_of_missing:.1f}%, Diverted {pct_diverted_of_missing:.1f}%")

Filas sin coords: 78,336 / 6,185,869 (1.266%)
De esas: Cancelled 0.0%, Diverted 0.0%

In [19]:
df_no_missing_coords = df_merged.dropna(subset=['origin_lat','dest_lat']).reset_index(drop=True)
print(f"Shape tras dropna: {df_no_missing_coords.shape[0]:,} filas")

Shape tras dropna: 6,107,533 filas

In [20]:
df_clean = df_no_missing_coords.copy()

##### **Informacion relevante para la Union con Informacion de la FAA**

Chequeo valores unicos de Airline o de Tail Number para poder usarlos en la busqueda de modelo dentro del extraction1.py

In [21]:
df_clean['Airline'].unique()

array(['SkyWest Airlines Inc.', 'Horizon Air', 'United Air Lines Inc.',
       'Commutair Aka Champlain Enterprises, Inc.',
       'GoJet Airlines, LLC d/b/a United Express',
       'Air Wisconsin Airlines Corp', 'Southwest Airlines Co.',
       'Mesa Airlines Inc.', 'Republic Airlines', 'Spirit Air Lines',
       'Delta Air Lines Inc.', 'Frontier Airlines Inc.', 'Allegiant Air',
       'Hawaiian Airlines Inc.', 'Envoy Air', 'Comair Inc.',
       'Endeavor Air Inc.', 'American Airlines Inc.',
       'Capital Cargo International', 'Alaska Airlines Inc.',
       'JetBlue Airways', 'Empire Airlines Inc.'], dtype=object)

In [22]:
df_clean['Tail_Number'].nunique()

5752

In [23]:
tail_numbers = df_clean['Tail_Number'].dropna().unique().tolist()
print(tail_numbers)

['N728SK', 'N752SK', 'N766SK', 'N752EV', 'N715SK', 'N744SK', 'N727SK', 'N771SK', 'N614SK', 'N773SK', 'N762SK', 'N730SK', 'N741EV', 'N716SK', 'N631SK', 'N772SK', 'N732SK', 'N709SK', 'N710SK', 'N774SK', 'N713SK', 'N763SK', 'N712SK', 'N776SK', 'N755EV', 'N738SK', 'N744EV', 'N755SK', 'N706SK', 'N606SK', 'N750SK', 'N740EV', 'N770SK', 'N761ND', 'N767SK', 'N701SK', 'N750EV', 'N718SK', 'N748SK', 'N751EV', 'N753EV', 'N745SK', 'N748EV', 'N740SK', 'N756SK', 'N703SK', 'N760EV', 'N758EV', 'N754SK', 'N746SK', 'N719SK', 'N760SK', 'N724SK', 'N702SK', 'N630SK', 'N742SK', 'N751SK', 'N730EV', 'N633SK', 'N759EV', 'N778SK', 'N632SK', 'N753SK', 'N768SK', 'N722EV', 'N716EV', 'N603SK', 'N707SK', 'N708SK', 'N726SK', 'N717EV', 'N754EV', 'N264SY', 'N278SY', 'N241SY', 'N308SY', 'N276SY', 'N837SK', 'N240SY', 'N263SY', 'N258SY', 'N303SY', 'N273SY', 'N838SK', 'N692CA', 'N170PQ', 'N299SY', 'N275SY', 'N277SY', 'N271SY', 'N161PQ', 'N609SK', 'N283SY', 'N839SK', 'N832SK', 'N281SY', 'N255SY', 'N267SY', 'N187PQ', 'N301SY', 'N806SK', 'N247SY', 'N824SK', 'N297SY', 'N840SK', 'N817SK', 'N287SY', 'N280SY', 'N274SY', 'N282SY', 'N256SY', 'N834SK', 'N284SY', 'N270SY', 'N295SY', 'N262SY', 'N292SY', 'N279SY', 'N305SY', 'N254SY', 'N833SK', 'N289SY', 'N269SY', 'N608SK', 'N300SY', 'N829SK', 'N288SY', 'N294SY', 'N296SY', 'N265SY', 'N290SY', 'N823SK', 'N291SY', 'N306SY', 'N246SY', 'N257SY', 'N243SY', 'N307SY', 'N836SK', 'N822SK', 'N302SY', 'N603CZ', 'N816SK', 'N251SY', 'N693CA', 'N804SK', 'N802SK', 'N286SY', 'N679CA', 'N285SY', 'N641CA', 'N827SK', 'N607SK', 'N242SY', 'N607CZ', 'N260SY', 'N304SY', 'N261SY', 'N931EV', 'N921EV', 'N919EV', 'N926EV', 'N922EV', 'N923EV', 'N917EV', 'N272SY', 'N831SK', 'N554CA', 'N244SY', 'N813SK', 'N604CZ', 'N253SY', 'N298SY', 'N250SY', 'N252SY', 'N805SK', 'N809SK', 'N830SK', 'N936EV', 'N293SY', 'N259SY', 'N549CA', 'N800SK', 'N821SK', 'N689CA', 'N820SK', 'N268SY', 'N826SK', 'N162PQ', 'N825SK', 'N803SK', 'N625CA', 'N221PS', 'N609UX', 'N167SY', 'N160SY', 'N133SY', 'N125SY', 'N150SY', 'N937EV', 'N795SK', 'N783SK', 'N789SK', 'N594SW', 'N207PS', 'N856AS', 'N130SY', 'N652BR', 'N926SW', 'N796SK', 'N797SK', 'N139SY', 'N113SY', 'N877AS', 'N116SY', 'N779SK', 'N788SK', 'N790SK', 'N906EV', 'N204SY', 'N784SK', 'N602UX', 'N792SK', 'N121SY', 'N876AS', 'N127SY', 'N168SY', 'N787SK', 'N618UX', 'N786SK', 'N134SY', 'N163SY', 'N207SY', 'N785SK', 'N606UX', 'N132SY', 'N103SY', 'N107SY', 'N259PS', 'N206SY', 'N117SY', 'N162SY', 'N108SY', 'N145SY', 'N920EV', 'N223JS', 'N916EV', 'N905EV', 'N793SK', 'N246PS', 'N110SY', 'N782SK', 'N109SY', 'N138SY', 'N143SY', 'N604UX', 'N612UX', 'N211SY', 'N144SY', 'N780SK', 'N616UX', 'N165SY', 'N614UX', 'N610UX', 'N156SY', 'N149SY', 'N135SY', 'N119SY', 'N621UX', 'N151SY', 'N743SK', 'N122SY', 'N608UX', 'N164SY', 'N601UX', 'N208SY', 'N909EV', 'N128SY', 'N624UX', 'N200SY', 'N106SY', 'N124SY', 'N603UX', 'N148SY', 'N607UX', 'N120SY', 'N202SY', 'N118SY', 'N141SY', 'N794SK', 'N623UX', 'N620UX', 'N140SY', 'N625UX', 'N617UX', 'N154SY', 'N213SY', 'N613UX', 'N161SY', 'N146SY', 'N166SY', 'N209SY', 'N900EV', 'N933EV', 'N615UX', 'N152SY', 'N605UX', 'N131SY', 'N142SY', 'N205SY', 'N868AS', 'N903EV', 'N879AS', 'N622UX', 'N153SY', 'N114SY', 'N611UX', 'N157SY', 'N914EV', 'N136SY', 'N203SY', 'N619UX', 'N105SY', 'N854AS', 'N863AS', 'N679SA', 'N976SW', 'N910SW', 'N946SW', 'N443SW', 'N693BR', 'N983SW', 'N955SW', 'N932SW', 'N874AS', 'N927SW', 'N915EV', 'N953SW', 'N923SW', 'N945SW', 'N479CA', 'N457SW', 'N472CA', 'N709BR', 'N912EV', 'N699BR', 'N487CA', 'N964SW', 'N465SW', 'N453SW', 'N889AS', 'N980SW', 'N961SW', 'N432SW', 'N471CA', 'N809CA', 'N431SW', 'N929EV', 'N919SW', 'N947SW', 'N920SW', 'N975SW', 'N437SW', 'N928EV', 'N468CA', 'N917SW', 'N455SW', 'N973SW', 'N939SW', 'N969SW', 'N913EV', 'N494CA', 'N959SW', 'N438SW', 'N979SW', 'N452SW', 'N905SW', 'N430SW', 'N903SW', 'N963SW', 'N986SW', 'N971SW', 'N440SW', 'N433SW', 'N910EV', 'N929SW', 'N982SW', 'N960SW', 'N466SW', 'N930SW', 'N932EV', 'N463SW', 'N869AS', 'N875AS', 'N925SW', 'N492SW', 'N701BR', 'N970SW', 'N417SW', 'N464SW', 'N967SW', 'N454SW', 'N593ML', 'N435SW', 'N978SW', 'N944SW', 'N957SW', 'N965SW', 'N951SW', 'N924SW', 'N958SW', 'N909SW', 'N758SK', 'N896SK', 'N374CA', 'N705SK', 'N898SK', 'N738EV', 'N604SK', 'N897SK', 'N191SY', 'N405SY', 'N177SY', 'N175SY', 'N404SY', 'N198SY', 'N193SY', 'N189SY', 'N183SY', 'N194SY', 'N187SY', 'N170SY', 'N181SY', 'N173SY', 'N197SY', 'N186SY', 'N185SY', 'N171SY', 'N195SY', 'N182SY', 'N174SY', 'N403SY', 'N400SY', 'N188SY', 'N199SY', 'N179SY', 'N176SY', 'N402SY', 'N184SY', 'N192SY', 'N178SY', 'N196SY', 'N656CA', 'N429SW', 'N459SW', 'N447SW', 'N496CA', 'N445SW', 'N886AS', 'N446SW', 'N477CA', 'N461SW', 'N907SW', 'N506CA', 'N779CA', 'N885AS', 'N439SW', 'N460SW', 'N702BR', 'N441SW', 'N498CA', 'N448SW', 'N936SW', 'N442SW', 'N402QX', 'N432QX', 'N443QX', 'N643QX', 'N453QX', 'N627QX', 'N635QX', 'N638QX', 'N647QX', 'N623QX', 'N639QX', 'N632QX', 'N436QX', 'N445QX', 'N650QX', 'N400QX', 'N403QX', 'N404QX', 'N422QX', 'N649QX', 'N620QX', 'N637QX', 'N633QX', 'N451QX', 'N625QX', 'N651QX', 'N421QX', 'N447QX', 'N405QX', 'N628QX', 'N630QX', 'N446QX', 'N448QX', 'N646QX', 'N644QX', 'N441QX', 'N645QX', 'N642QX', 'N648QX', 'N629QX', 'N624QX', 'N626QX', 'N438QX', 'N634QX', 'N450QX', 'N631QX', 'N622QX', 'N401QX', 'N452QX', 'N437QX', 'N440QX', 'N442QX', 'N427QX', 'N439QX', 'N412QX', 'N641QX', 'N426QX', 'N430QX', 'N636QX', 'N444QX', 'N434MK', 'N435QX', 'N37502', 'N11206', 'N405UA', 'N77258', 'N899UA', 'N467UA', 'N829UA', 'N12218', 'N17233', 'N453UA', 'N66841', 'N76514', 'N27526', 'N809UA', 'N459UA', 'N68802', 'N68843', 'N27213', 'N73283', 'N75429', 'N424UA', 'N77430', 'N75435', 'N16732', 'N69818', 'N77022', 'N27519', 'N66831', 'N14106', 'N68821', 'N895UA', 'N26910', 'N443UA', 'N87512', 'N37252', 'N14001', 'N893UA', 'N826UA', 'N33266', 'N811UA', 'N17529', 'N881UA', 'N4901U', 'N76517', 'N47517', 'N87507', 'N57016', 'N77865', 'N66814', 'N38446', 'N37522', 'N74856', 'N78448', 'N75428', 'N830UA', 'N78285', 'N69888', 'N73270', 'N78511', 'N27503', 'N36247', 'N35204', 'N417UA', 'N828UA', 'N448UA', 'N38467', 'N63820', 'N35236', 'N14228', 'N818UA', 'N56859', 'N69847', 'N69819', 'N460UA', 'N816UA', 'N27246', 'N2749U', 'N77261', 'N67845', 'N39728', 'N836UA', 'N75854', 'N890UA', 'N37523', 'N34455', 'N17719', 'N76269', 'N454UA', 'N808UA', 'N76288', 'N27520', 'N835UA', 'N77539', 'N14240', 'N449UA', 'N28478', 'N76265', 'N28457', 'N37528', 'N879UA', 'N73275', 'N86534', 'N66897', 'N47524', 'N69824', 'N38473', 'N817UA', 'N57870', 'N62883', 'N12754', 'N47414', 'N76508', 'N412UA', 'N61886', 'N73276', 'N61887', 'N61882', 'N37465', 'N57852', 'N57111', 'N37510', 'N37427', 'N36476', 'N26215', 'N66893', 'N14237', 'N833UA', 'N67501', 'N57857', 'N37466', 'N423UA', 'N38443', 'N28912', 'N39423', 'N36444', 'N894UA', 'N47512', 'N78438', 'N77536', 'N37513', 'N75432', 'N62896', 'N64809', 'N41135', 'N87531', 'N889UA', 'N854UA', 'N848UA', 'N77530', 'N75433', 'N802UA', 'N874UA', 'N37507', 'N38479', 'N648UA', 'N68452', 'N13110', 'N18243', 'N39415', 'N674UA', 'N69885', 'N17133', 'N485UA', 'N33284', 'N675UA', 'N58101', 'N76502', 'N27421', 'N27511', 'N39416', 'N75426', 'N12221', 'N69810', 'N37462', 'N76254', 'N36469', 'N34222', 'N17229', 'N823UA', 'N37277', 'N14231', 'N457UA', 'N73445', 'N12225', 'N62849', 'N33289', 'N404UA', 'N26210', 'N26909', 'N76503', 'N77871', 'N489UA', 'N76523', 'N671UA', 'N68807', 'N16234', 'N57863', 'N2639U', 'N17245', 'N77525', 'N14242', 'N462UA', 'N66837', 'N898UA', 'N17753', 'N69813', 'N29978', 'N75851', 'N27205', 'N464UA', 'N33209', 'N825UA', 'N76519', 'N880UA', 'N68891', 'N37525', 'N27515', 'N54711', 'N871UA', 'N33203', 'N23707', 'N76526', 'N408UA', 'N16703', 'N896UA', 'N68817', 'N851UA', 'N37422', 'N852UA', 'N57864', 'N444UA', 'N827UA', 'N471UA', 'N814UA', 'N68842', 'N37263', 'N466UA', 'N63899', 'N27015', 'N87513', 'N13138', 'N821UA', 'N891UA', 'N37274', 'N36272', 'N26226', 'N406UA', 'N832UA', 'N413UA', 'N17244', 'N81449', 'N425UA', 'N64844', 'N76528', 'N470UA', 'N456UA', 'N37527', 'N73251', 'N61881', 'N37470', 'N63890', 'N75861', 'N68823', 'N78506', 'N36207', 'N820UA', 'N23708', 'N824UA', 'N68822', 'N37290', 'N38257', 'N438UA', 'N812UA', 'N14230', 'N13720', 'N62884', 'N897UA', 'N14115', 'N37419', 'N67846', 'N67812', 'N69804', 'N18220', 'N422UA', 'N38268', 'N403UA', 'N839UA', 'N37521', 'N465UA', 'N14214', 'N468UA', 'N75853', 'N24972', 'N39463', 'N401UA', 'N419UA', 'N834UA', 'N13227', 'N12216', 'N4888U', 'N38454', 'N416UA', 'N420UA', 'N37516', 'N78509', 'N37518', 'N452UA', 'N892UA', 'N12125', 'N407UA', 'N37504', 'N878UA', 'N36472', 'N27477', 'N12012', 'N25705', 'N77542', 'N76010', 'N78003', 'N47505', 'N17139', 'N1902U', 'N37471', 'N819UA', 'N62895', 'N39475', 'N45440', 'N24202', 'N39418', 'N45905', 'N69830', 'N87527', 'N12238', 'N76021', 'N53441', 'N78540', 'N69806', 'N429UA', 'N77537', 'N69840', 'N57439', 'N2331U', 'N37437', 'N875UA', 'N411UA', 'N445UA', 'N643UA', 'N657UA', 'N469UA', 'N12114', 'N426UA', 'N33103', 'N66828', 'N26208', 'N30913', 'N68811', 'N12003', 'N458UA', 'N77520', 'N78001', 'N75858', 'N14249', 'N37287', 'N34460', 'N2748U', 'N68805', 'N446UA', 'N66803', 'N16701', 'N69835', 'N15751', 'N76529', 'N24715', 'N37420', 'N16217', 'N69816', 'N845UA', 'N877UA', 'N655UA', 'N37253', 'N77538', 'N26232', 'N402UA', 'N677UA', 'N78866', 'N38458', 'N17730', 'N76533', 'N876UA', 'N494UA', 'N62889', 'N61898', 'N77518', 'N17104', 'N76505', 'N75436', 'N418UA', 'N428UA', 'N37464', 'N27239', 'N76532', 'N62894', 'N67815', 'N65832', 'N38451', 'N33286', 'N26967', 'N13750', 'N658UA', 'N37273', 'N14235', 'N76515', 'N29907', 'N451UA', 'N75425', 'N37474', 'N13248', 'N447UA', 'N27903', 'N77510', 'N414UA', 'N77535', 'N26952', 'N641UA', 'N656UA', 'N37506', 'N27509', 'N37530', 'N57855', 'N33262', 'N492UA', 'N801UA', 'N15712', 'N13716', 'N76516', 'N12109', 'N17105', 'N54241', 'N24736', 'N642UA', 'N810UA', 'N67827', 'N16709', 'N19136', 'N14250', 'N17752', 'N27734', 'N24973', 'N35271', 'N35260', 'N472UA', 'N37456', 'N14735', 'N493UA', 'N831UA', 'N14731', 'N68801', 'N66808', 'N24211', 'N488UA', 'N53442', 'N76522', 'N79541', 'N78501', 'N427UA', 'N669UA', 'N667UA', 'N2846U', 'N23721', 'N660UA', 'N461UA', 'N24224', 'N12006', 'N473UA', 'N39461', 'N76504', 'N2333U', 'N73256', 'N26960', 'N38417', 'N26906', 'N24729', 'N48127', 'N14704', 'N38424', 'N15710', 'N33714', 'N15969', 'N38459', 'N670UA', 'N24980', 'N24976', 'N62892', 'N38950', 'N13718', 'N497UA', 'N78524', 'N27965', 'N24974', 'N2140U', 'N37018', 'N807UA', 'N79521', 'N14107', 'N2534U', 'N24702', 'N37255', 'N77431', 'N647UA', 'N27958', 'N45956', 'N38727', 'N673UA', 'N91007', 'N27722', 'N440UA', 'N27724', 'N29971', 'N29961', 'N12010', 'N38955', 'N29977', 'N14011', 'N17963', 'N29984', 'N78009', 'N24706', 'N33264', 'N16008', 'N37298', 'N437UA', 'N78013', 'N24979', 'N66848', 'N20904', 'N37267', 'N482UA', 'N2135U', 'N29975', 'N2341U', 'N410UA', 'N853UA', 'N668UA', 'N463UA', 'N36447', 'N27908', 'N29981', 'N439UA', 'N2644U', 'N822UA', 'N27733', 'N2250U', 'N2136U', 'N27964', 'N78017', 'N13013', 'N29968', 'N12004', 'N2747U', 'N27957', 'N2251U', 'N12005', 'N25982', 'N2142U', 'N27959', 'N77019', 'N36962', 'N35953', 'N2645U', 'N2243U', 'N26970', 'N26966', 'N17002', 'N2352U', 'N23983', 'N16009', 'N2138U', 'N2737U', 'N19951', 'N13954', 'N12157', 'N14143', 'N14204', 'N17138', 'N11176', 'N11187', 'N12195', 'N12136', 'N11193', 'N11150', 'N16151', 'N14162', 'N11113', 'N14186', 'N17159', 'N11181', 'N13913', 'N14158', 'N12160', 'N14173', 'N11194', 'N15910', 'N16147', 'N14125', 'N23139', 'N21144', 'N13132', 'N33182', 'N17169', 'N11137', 'N12142', 'N14198', 'N14174', 'N27152', 'N14168', 'N17146', 'N11165', 'N11199', 'N11535', 'N27190', 'N14148', 'N21129', 'N524GJ', 'N554GJ', 'N538GJ', 'N520GJ', 'N546GJ', 'N543GJ', 'N540GJ', 'N521GJ', 'N506GJ', 'N552GJ', 'N511GJ', 'N501GJ', 'N519GJ', 'N547GJ', 'N548GJ', 'N535GJ', 'N530GJ', 'N533GJ', 'N542GJ', 'N544GJ', 'N541GJ', 'N502GJ', 'N551GJ', 'N549GJ', 'N536GJ', 'N537GJ', 'N522GJ', 'N534GJ', 'N504GJ', 'N502MJ', 'N532GJ', 'N21154', 'N16149', 'N12175', 'N13161', 'N16541', 'N11107', 'N12163', 'N410AW', 'N425AW', 'N438AW', 'N456ZW', 'N427ZW', 'N465AW', 'N453AW', 'N433AW', 'N423AW', 'N463AW', 'N450AW', 'N462AW', 'N449AW', 'N424AW', 'N439AW', 'N416AW', 'N442AW', 'N444ZW', 'N466AW', 'N458AW', 'N441ZW', 'N412AW', 'N428AW', 'N448AW', 'N454AW', 'N421ZW', 'N440AW', 'N413AW', 'N431AW', 'N426AW', 'N409AW', 'N436AW', 'N447AW', 'N455AW', 'N443AW', 'N446AW', 'N411ZW', 'N445AW', 'N420AW', 'N471ZW', 'N405AW', 'N467AW', 'N457AW', 'N429AW', 'N459AW', 'N464AW', 'N468AW', 'N437AW', 'N451AW', 'N419AW', 'N470ZW', 'N430AW', 'N21197', 'N14153', 'N16178', 'N523GJ', 'N545GJ', 'N539GJ', 'N507MJ', 'N531GJ', 'N460AW', 'N432AW', 'N418AW', 'N408AW', 'N414ZW', 'N415AW', 'N452AW', 'N11106', 'N11191', 'N553GJ', 'N503GJ', 'N461AW', 'N417AW', 'N508GJ', 'N16183', 'N13124', 'N14179', 'N469AW', 'N434AW', 'N435AW', 'N423WN', 'N496WN', 'N7732A', 'N8526W', 'N763SW', 'N8324A', 'N901WN', 'N8665D', 'N7843A', 'N798SW', 'N457WN', 'N947WN', 'N752SW', 'N488WN', 'N212WN', 'N219WN', 'N8581Z', 'N729SW', 'N224WN', 'N426WN', 'N266WN', 'N299WN', 'N487WN', 'N258WN', 'N269WN', 'N563WN', 'N7856A', 'N7836A', 'N238WN', 'N8532S', 'N8554X', 'N437WN', 'N7844A', 'N762SW', 'N8683D', 'N769SW', 'N243WN', 'N922WN', 'N720WN', 'N7815L', 'N946WN', 'N8623F', 'N454WN', 'N465WN', 'N969WN', 'N462WN', 'N8566Z', 'N252WN', 'N223WN', 'N8631A', 'N8614M', 'N227WN', 'N8531Q', 'N8693A', 'N8559Q', 'N944WN', 'N7704B', 'N7722B', 'N439WN', 'N914WN', 'N7832A', 'N966WN', 'N8578Q', 'N234WN', 'N218WN', 'N7829B', 'N902WN', 'N274WN', 'N727SW', 'N434WN', 'N8677A', 'N8510E', 'N7811F', 'N8517F', 'N8686A', 'N8657B', 'N932WN', 'N7825A', 'N424WN', 'N8539V', 'N8524Z', 'N7845A', 'N8577Z', 'N469WN', 'N8504G', 'N7876A', 'N8681M', 'N967WN', 'N938WN', 'N282WN', 'N748SW', 'N8645A', 'N255WN', 'N7824A', 'N716SW', 'N248WN', 'N478WN', 'N461WN', 'N737JW', 'N714CB', 'N7888A', 'N8547V', 'N968WN', 'N965WN', 'N8584Z', 'N948WN', 'N409WN', 'N7818L', 'N7812G', 'N8569Z', 'N8519R', 'N7725A', 'N8668A', 'N8582Z', 'N8640D', 'N557WN', 'N7875A', 'N950WN', 'N8633A', 'N8540V', 'N7816B', 'N8651A', 'N452WN', 'N283WN', 'N401WN', 'N7823A', 'N7854B', 'N8557Q', 'N480WN', 'N262WN', 'N481WN', 'N418WN', 'N8675A', 'N8615E', 'N8515X', 'N237WN', 'N917WN', 'N217JC', 'N8541W', 'N7736A', 'N7737E', 'N281WN', 'N926WN', 'N960WN', 'N754SW', 'N732SW', 'N245WN', 'N8518R', 'N718SW', 'N924WN', 'N486WN', 'N295WN', 'N773SA', 'N7846A', 'N906WN', 'N8637A', 'N449WN', 'N728SW', 'N781WN', 'N939WN', 'N7849A', 'N749SW', 'N7734H', 'N8580Z', 'N8625A', 'N416WN', 'N467WN', 'N485WN', 'N8576Z', 'N900WN', 'N8523W', 'N261WN', 'N8670A', 'N267WN', 'N940WN', 'N8529Z', 'N256WN', 'N954WN', 'N444WN', 'N8698B', 'N500WR', 'N431WN', 'N792SW', 'N8673F', 'N419WN', 'N964WN', 'N7833A', 'N958WN', 'N7826B', 'N8663A', 'N7731A', 'N8690A', 'N8562Z', 'N7865A', 'N7839A', 'N268WN', 'N8692F', 'N8511K', 'N8664J', 'N8624J', 'N8583Z', 'N8653A', 'N8550Q', 'N8628A', 'N8607M', 'N8643A', 'N294WN', 'N7863A', 'N8536Z', 'N8642E', 'N7864B', 'N8548P', 'N7848A', 'N8555Z', 'N210WN', 'N8630B', 'N8545V', 'N8600F', 'N8680C', 'N8602F', 'N8699A', 'N8660A', 'N959WN', 'N7730A', 'N8601C', 'N7740A', 'N7741C', 'N8689C', 'N7752B', 'N933WN', 'N254WN', 'N8502Z', 'N8549Z', 'N920WN', 'N941WN', 'N956WN', 'N8610A', 'N7813P', 'N8635F', 'N551WN', 'N8661A', 'N220WN', 'N476WN', 'N466WN', 'N904WN', 'N8514F', 'N8684F', 'N8616C', 'N8671D', 'N7835A', 'N8647A', 'N8656B', 'N272WN', 'N7869A', 'N420WN', 'N200WN', 'N765SW', 'N440LV', 'N7751A', 'N8513F', 'N8567Z', 'N8659D', 'N249WN', 'N912WN', 'N285WN', 'N7837A', 'N7715E', 'N8691A', 'N712SW', 'N785SW', 'N915WN', 'N495WN', 'N8508W', 'N8620H', 'N8649A', 'N8655D', 'N484WN', 'N8537Z', 'N936WN', 'N7842A', 'N955WN', 'N8679A', 'N8619F', 'N497WN', 'N8535S', 'N8696E', 'N755SA', 'N280WN', 'N222WN', 'N408WN', 'N7868K', 'N8525S', 'N8544Z', 'N8676A', 'N738CB', 'N8552Z', 'N499WN', 'N8503A', 'N7847A', 'N7879A', 'N474WN', 'N414WN', 'N747SA', 'N8674B', 'N473WN', 'N8685B', 'N734SA', 'N560WN', 'N406WN', 'N7886A', 'N962WN', 'N943WN', 'N8553W', 'N8546V', 'N7702A', 'N411WN', 'N7822A', 'N744SW', 'N8658A', 'N8611F', 'N923WN', 'N443WN', 'N7852A', 'N8652B', 'N711HK', 'N477WN', 'N7820L', 'N8697C', 'N8573Z', 'N767SW', 'N284WN', 'N8570W', 'N550WN', 'N942WN', 'N493WN', 'N8507C', 'N241WN', 'N8688J', 'N8575Z', 'N8678E', 'N8669B', 'N8646B', 'N8318F', 'N293WN', 'N930WN', 'N7878A', 'N8632A', 'N910WN', 'N204WN', 'N8512U', 'N953WN', 'N8626B', 'N8571Z', 'N8568Z', 'N8606C', 'N7827A', 'N7721E', 'N289CT', 'N8654B', 'N8667D', 'N7850B', 'N760SW', 'N279WN', 'N709SW', 'N8672F', 'N735SA', 'N8687A', 'N8520Q', 'N8538V', 'N8603F', 'N750SA', 'N717SA', 'N8551Q', 'N569WN', 'N758SW', 'N288WN', 'N949WN', 'N909WN', 'N8641B', 'N273WN', 'N251WN', 'N751SW', 'N8308K', 'N8644C', 'N555LV', 'N428WN', 'N8527Q', 'N927WN', 'N7733B', 'N8694E', 'N257WN', 'N458WN', 'N7855A', 'N236WN', 'N7851A', 'N410WN', 'N492WN', 'N8316H', 'N8321D', 'N8328A', 'N8305E', 'N8311Q', 'N8320J', 'N8327A', 'N8312C', 'N8326F', 'N8302F', 'N913WN', 'N7830A', 'N7748A', 'N483WN', 'N201LV', 'N286WN', 'N259WN', 'N8561Z', 'N8682B', 'N240WN', 'N934WN', 'N8509U', 'N403WN', 'N441WN', 'N8618N', 'N235WN', 'N745SW', 'N8528Q', 'N435WN', 'N264LV', 'N7713A', 'N8613K', 'N421LV', 'N7738A', 'N211WN', 'N415WN', 'N260WN', 'N463WN', 'N566WN', 'N8319F', 'N8307K', 'N8317M', 'N736SA', 'N8604K', 'N8605E', 'N951WN', 'N275WN', 'N931WN', 'N427WN', 'N202WN', 'N498WN', 'N429WN', 'N8639B', 'N8329B', 'N8621A', 'N226WN', 'N432WN', 'N725SW', 'N957WN', 'N730SW', 'N7877H', 'N556WN', 'N7881A', 'N8315C', 'N8560Z', 'N8638A', 'N8322X', 'N8650F', 'N8313F', 'N8310C', 'N287WN', 'N413WN', 'N221WN', 'N442WN', 'N233LV', 'N8695D', 'N564WN', 'N291WN', 'N8563Z', 'N8530W', 'N271LV', 'N8542Z', 'N7735A', 'N8501V', 'N430WN', 'N963WN', 'N8543Z', 'N407WN', 'N8579Z', 'N7866A', 'N297WN', 'N228WN', 'N8622A', 'N479WN', 'N8565Z', 'N276WN', 'N8629A', 'N7828A', 'N952WN', 'N242WN', 'N928WN', 'N8572X', 'N239WN', 'N490WN', 'N229WN', 'N567WN', 'N290WN', 'N8325D', 'N562WN', 'N8301J', 'N8303R', 'N8627B', 'N724SW', 'N7840A', 'N8323C', 'N8309C', 'N8306H', 'N7883A', 'N7742B', 'N8634A', 'N8556Z', 'N246LV', 'N470WN', 'N7862A', 'N7880D', 'N225WN', 'N929WN', 'N203WN', 'N231WN', 'N7726A', 'N296WN', 'N7859B', 'N205WN', 'N253WN', 'N8558Z', 'N494WN', 'N482WN', 'N7739A', 'N8534Z', 'N8314L', 'N559WN', 'N7720F', 'N908WN', 'N475WN', 'N422WN', 'N8574Z', 'N907WN', 'N8617E', 'N7841A', 'N8608N', 'N733SA', 'N412WN', 'N7724A', 'N425LV', 'N8522P', 'N417WN', 'N8648A', 'N232WN', 'N919WN', 'N7727A', 'N265WN', 'N7723E', 'N230WN', 'N244WN', 'N558WN', 'N757LV', 'N292WN', 'N464WN', 'N7874B', 'N8564Z', 'N903WN', 'N7743B', 'N945WN', 'N565WN', 'N8533S', 'N247WN', 'N298WN', 'N7884G', 'N7858A', 'N7744A', 'N7749B', 'N7729A', 'N731SA', 'N7747C', 'N961WN', 'N799SW', 'N7750A', 'N7867A', 'N404WN', 'N215WN', 'N8731J', 'N7745A', 'N8742M', 'N278WN', 'N7857B', 'N8732S', 'N8738K', 'N8735L', 'N7746C', 'N8800L', 'N250WN', 'N925WN', 'N8743K', 'N8609A', 'N8702L', 'N8736J', 'N8739L', 'N935WN', 'N7728D', 'N277WN', 'N8740A', 'N405WN', 'N8730Q', 'N8748Q', 'N8801Q', 'N8744B', 'N8734Q', 'N8737L', 'N8741L', 'N8817L', 'N213WN', 'N209WN', 'N8745K', 'N8612K', 'N8818Q', 'N8803L', 'N937WN', 'N214WN', 'N436WN', 'N8746Q', 'N8662F', 'N438WN', 'N8726H', 'N8750Q', 'N8724J', 'N8722L', 'N8802Q', 'N8747Q', 'N8718Q', 'N8749Q', 'N746SW', 'N80343', 'N85358', 'N86334', 'N87303', 'N82338', 'N89342', 'N86309', 'N87302', 'N84307', 'N87339', 'N86372', 'N89313', 'N89357', 'N88301', 'N82333', 'N87353', 'N85340', 'N86350', 'N85369', 'N88310', 'N78361', 'N88341', 'N88328', 'N86336', 'N87367', 'N86371', 'N85374', 'N88346', 'N93305', 'N85363', 'N86347', 'N89304', 'N86322', 'N86316', 'N85354', 'N89362', 'N86312', 'N86311', 'N85351', 'N85370', 'N88330', 'N82314', 'N87319', 'N87306', 'N87364', 'N87360', 'N80348', 'N86324', 'N85352', 'N82366', 'N88359', 'N85356', 'N89315', 'N85373', 'N86344', 'N88327', 'N88326', 'N89317', 'N85376', 'N87337', 'N87345', 'N87365', 'N85355', 'N85323', 'N88335', 'N87368', 'N89349', 'N87318', 'N88325', 'N88332', 'N83329', 'N86375', 'N88331', 'N85320', 'N89321', 'N946LR', 'N326MS', 'N917FJ', 'N913FJ', 'N939LR', 'N915FJ', 'N914FJ', 'N952LR', 'N904FJ', 'N905J', 'N957LR', 

In [24]:
import re
import pandas as pd

def normalize_tail(s):
    if pd.isna(s): return s
    s = str(s).strip().upper()
    s = re.sub(r'[^A-Z0-9]', '', s)
    if s == '': return s
    if s[0].isdigit(): s = 'N' + s
    if s.startswith('NN'): s = s[1:]
    return s

df = df_clean.copy()
faa = pd.read_csv("raw data/faa_tailnumbers_filtered.csv", dtype=str, low_memory=False)

# Normalizar matrículas en df
df['Tail_Number_norm'] = df['Tail_Number'].astype(str).apply(normalize_tail)

# Detectar columna matrícula en FAA y normalizar
orig_cols = list(faa.columns)
cols_map = {c.lower().replace(' ','').replace('-','').replace('_',''): c for c in orig_cols}
candidates_n = ['n-number','n_number','nnumber','registration','registrationnumber','nnum','n']
col_n = next((cols_map[c] for c in candidates_n if c in cols_map), None)
if col_n is None:
    for c in orig_cols:
        sample = faa[c].dropna().astype(str).head(50).tolist()
        if sample and sum(bool(re.search(r'[A-Z]', v) and re.search(r'\d', v)) for v in sample) >= 3:
            col_n = c
            break
if col_n is None:
    col_n = orig_cols[0]

faa['N_NUMBER_norm'] = faa[col_n].astype(str).apply(normalize_tail)

# Detectar columnas model y year en FAA
col_model = next((cols_map[c] for c in ['model','mfr_mdl_code','maker','modelname','aircraftmodel','mfr_model','mfrmdlcode'] if c in cols_map), None)
col_year  = next((cols_map[c] for c in ['yearmfr','year','year_mfr','manufactureyear','yearmanufactured','yearmfg'] if c in cols_map), None)

faa['MODEL'] = faa[col_model].astype(str).str.strip() if col_model else pd.NA
faa['YEAR_MFR'] = faa[col_year].astype(str).str.strip() if col_year else pd.NA

# Merge por matrícula normalizada
faa_for_merge = faa[['N_NUMBER_norm','MODEL','YEAR_MFR']].rename(columns={'N_NUMBER_norm':'N_NUMBER'})
df = df.merge(faa_for_merge, how='left', left_on='Tail_Number_norm', right_on='N_NUMBER')

# Calcular aircraft_age
df['FlightDate'] = pd.to_datetime(df.get('FlightDate', pd.Series()), errors='coerce')
df['YEAR_MFR'] = pd.to_numeric(df['YEAR_MFR'], errors='coerce')
df['aircraft_age'] = df['FlightDate'].dt.year - df['YEAR_MFR']

# Cobertura compacta
total = len(df)
from_faa = df['MODEL'].notna().sum()
print(f"Total filas: {total}")
print(f"Coincidencias con FAA (modelo encontrado): {from_faa}")
print(f"Sin match (modelo NaN): {total - from_faa}")
print(f"Porcentaje de cobertura: {from_faa/total:.2%}")

# Inferir modelos faltantes por Operating_Airline (fallback global si hace falta)
air_col = next((c for c in df.columns if c.lower() in ('operating_airline','operator','airline','operatingcarrier')), None)
df['Operating_Airline'] = df[air_col].astype(str).fillna('UNKNOWN') if air_col else 'UNKNOWN'

mode_by_airline = (df[df['MODEL'].notna()]
                   .groupby('Operating_Airline')['MODEL']
                   .agg(lambda s: s.mode().iat[0] if not s.mode().empty else pd.NA)
                   .to_dict())

global_mode = df['MODEL'].dropna().mode()
global_mode = global_mode.iat[0] if not global_mode.empty else pd.NA

def infer_model(row):
    if pd.notna(row['MODEL']) and str(row['MODEL']).lower() != 'nan': return row['MODEL']
    a = row['Operating_Airline']
    if a in mode_by_airline and pd.notna(mode_by_airline[a]): return mode_by_airline[a]
    return global_mode

df['MODEL_final'] = df.apply(infer_model, axis=1)
df['MODEL_source'] = df.apply(lambda r: 'faa' if pd.notna(r['MODEL']) and str(r['MODEL']).lower()!='nan' else ('inferred' if pd.notna(r['MODEL_final']) else 'missing'), axis=1)

# Resultado final: solo las columnas solicitadas
out = df[['Tail_Number_norm','N_NUMBER','MODEL','YEAR_MFR','aircraft_age','MODEL_final','MODEL_source']].copy()

from_faa = (out['MODEL_source']=='faa').sum()
inferred = (out['MODEL_source']=='inferred').sum()
final_coverage = (from_faa + inferred) / total if total else 0
print(f"Model desde FAA: {from_faa} ({from_faa/total:.2%})")
print(f"Model inferidos: {inferred} ({inferred/total:.2%})")
print(f"Cobertura final (FAA + inferidos): {final_coverage:.2%}")

Total filas: 6107533
Coincidencias con FAA (modelo encontrado): 5607824
Sin match (modelo NaN): 499709
Porcentaje de cobertura: 91.82%
Model desde FAA: 5607824 (91.82%)
Model inferidos: 499709 (8.18%)
Cobertura final (FAA + inferidos): 100.00%

In [25]:
df['MODEL_final'].isnull().sum()

0

In [26]:
cols_to_drop = ['Tail_Number_norm','N_NUMBER','YEAR_MFR','MODEL','MODEL_source']
existing = [c for c in cols_to_drop if c in df.columns]
df.drop(columns=existing, inplace=True)
df.rename(columns={'MODEL_final':'MODEL'}, inplace=True)
df.head()

,FlightDate,sched_dep_dt,sched_arr_dt,dep_dt,arr_dt,Airline,Origin,Dest,Cancelled,Diverted,DepDelayMinutes,DepDelay,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,origin_lat,origin_lon,dest_lat,dest_lon,aircraft_age,MODEL
0,2021-03-03,2021-03-03 07:24:00,2021-03-03 08:43:00,2021-03-03 07:14:00,2021-03-03 08:18:00,SkyWest Airlines Inc.,SGU,PHX,0,0,0.0,-10.0,0.0,49.0,79.0,64.0,262.0,AA,AA_CODESHARE,19805,AA,3133,SkyWest Airlines Inc.,20304,OO,N728SK,3133,14794,1479405,34794,"St. George, UT",UT,49,Utah,87,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,0.0,-1.0,0700-0759,10.0,724.0,813.0,5.0,-25.0,0.0,-2.0,0800-0859,2,0.0,37.036389,-113.510306,33.435302,-112.005905,16.0,CL-600-2C10
1,2021-03-03,2021-03-03 09:22:00,2021-03-03 10:40:00,2021-03-03 09:17:00,2021-03-03 10:31:00,SkyWest Airlines Inc.,PHX,SGU,0,0,0.0,-5.0,0.0,48.0,78.0,74.0,262.0,AA,AA_CODESHARE,19805,AA,3134,SkyWest Airlines Inc.,20304,OO,N752SK,3134,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,14794,1479405,34794,"St. George, UT",UT,49,Utah,87,0.0,-1.0,0900-0959,23.0,940.0,1028.0,3.0,-9.0,0.0,-1.0,1000-1059,2,0.0,33.435302,-112.005905,37.036389,-113.510306,16.0,CL-600-2C10
2,2021-03-03,2021-03-03 13:30:00,2021-03-03 15:30:00,2021-03-03 13:21:00,2021-03-03 15:01:00,SkyWest Airlines Inc.,MHT,ORD,0,0,0.0,-9.0,0.0,129.0,180.0,160.0,843.0,AA,AA_CODESHARE,19805,AA,3135,SkyWest Airlines Inc.,20304,OO,N766SK,3135,13296,1329604,30721,"Manchester, NH",NH,33,New Hampshire,14,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,1300-1359,15.0,1336.0,1445.0,16.0,-29.0,0.0,-2.0,1500-1559,4,0.0,42.932598,-71.435699,41.978600,-87.904800,16.0,CL-600-2C10
3,2021-03-03,2021-03-03 16:45:00,2021-03-03 20:10:00,2021-03-03 16:36:00,2021-03-03 20:02:00,SkyWest Airlines Inc.,DFW,TRI,0,0,0.0,-9.0,0.0,112.0,145.0,146.0,868.0,AA,AA_CODESHARE,19805,AA,3136,SkyWest Airlines Inc.,20304,OO,N752EV,3136,11298,1129806,30194,"Dallas/Fort Worth, TX",TX,48,Texas,74,15323,1532305,35323,"Bristol/Johnson City/Kingsport, TN",TN,47,Tennessee,54,0.0,-1.0,1600-1659,27.0,1703.0,1955.0,7.0,-8.0,0.0,-1.0,2000-2059,4,0.0,32.896801,-97.038002,36.475201,-82.407401,NaN,CL-600-2C10
4,2021-03-03,2021-03-03 18:44:00,2021-03-03 19:25:00,2021-03-03 18:38:00,2021-03-03 19:03:00,SkyWest Airlines Inc.,PHX,BFL,0,0,0.0,-6.0,0.0,69.0,101.0,85.0,425.0,AA,AA_CODESHARE,19805,AA,3137,SkyWest Airlines Inc.,20304,OO,N715SK,3137,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,10561,1056103,30561,"Bakersfield, CA",CA,6,California,91,0.0,-1.0,1800-1859,13.0,1851.0,1900.0,3.0,-22.0,0.0,-2.0,1900-1959,2,0.0,33.435302,-112.005905,35.433601,-119.056999,17.0,CL-600-2C10

**Ultimas transformaciones**

In [27]:
# Crear la nueva columna como suma de DepDelayMinutes y ArrDelayMinutes
df['TotalDelayMinutes'] = df['DepDelayMinutes'].fillna(0) + df['ArrDelayMinutes'].fillna(0)

# Reordenar columnas para que TotalDelayMinutes quede después de ArrDelayMinutes
cols = list(df.columns)
pos = cols.index('ArrDelayMinutes') + 1
cols = cols[:pos] + ['TotalDelayMinutes'] + cols[pos:]
df = df[cols]

# Verificar resultado
print(df[['DepDelayMinutes','ArrDelayMinutes','TotalDelayMinutes']].head())


df.drop(columns=['Diverted','Cancelled'], inplace=True)

   DepDelayMinutes  ArrDelayMinutes  TotalDelayMinutes  TotalDelayMinutes
0              0.0              0.0                0.0                0.0
1              0.0              0.0                0.0                0.0
2              0.0              0.0                0.0                0.0
3              0.0              0.0                0.0                0.0
4              0.0              0.0                0.0                0.0

In [28]:
df.to_csv("Dataset_OData_Final_Martin_Otero.csv", index=False)